app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::auth();
Route::post('/logout', 'Auth\AuthController@logout');
Route::group(['middleware'=>'auth'], function(){


Route::get('/', 'KelasController@index');
Route::get('kelas/add', 'KelasController@create');
Route::post('kelas/add', 'KelasController@store');
Route::delete('kelas/{id}/delete', 'KelasController@destroy');
Route::get('kelas/{id}/edit', 'KelasController@edit');
Route::patch('kelas/{id}/edit', 'KelasController@update');


Route::get('siswa','SiswaController@index');
Route::get('siswa/add', 'SiswaController@create');
Route::post('siswa/add', 'SiswaController@store');
Route::delete('siswa/{nis}/delete', 'SiswaController@destroy');
Route::get('siswa/{nis}/edit', 'SiswaController@edit');
Route::patch('siswa/{nis}/edit', 'SiswaController@update');
});

app/Kelas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    public $primaryKey = 'id_kelas';
    
    protected $table = 't_kelas';
    
    protected $fillable = [
        'nama_kelas', 'jurusan'
    ];
}

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    public $primaryKey = 'nis';
    
    protected $table = 't_siswa';
    
    protected $fillable = [
        'nis','nama_lengkap','jenis_kelamin','alamat','no_telp','id_kelas','foto'
    ];
    
    public function getJenisKelaminDisplayAttribute(){
        if(@$this->attributes['jenis_kelamin'] == 'L') return 'Laki-Laki';
        if(@$this->attributes['jenis_kelamin'] == 'P') return 'Perempuan';
        return '-';
    }
    
    public function kelas()
    {
        return $this->hasOne('\App\Kelas' , 'id_kelas','id_kelas');
    }
}

app/User.php
<?php

namespace App;

// use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

    // use Notifiable;

    protected $table = 't_login';
    public $primaryKey = 'id_login';
    protected $fillable = ['username', 'nama_user', 'password'];


    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class KelasController extends Controller
{
    public function index()
    {
        $data['result'] = \App\Kelas::all();
        return view('kelas/index')->with($data);
    }
    
    public function create()
    {
        return view('kelas/form');
    }
    
    public function store(Request $request){
        
        $rules = [
            'nama_kelas' => 'required|max:100',
            'jurusan' => 'required|max:100'
        ];
        $this->validate($request, $rules);
        
        $input = $request->all();
        $status = \App\Kelas::create($input);
        if($status) return redirect('/')->with('success', 'Data berhasil ditambahkan');
        else return redirect('/')->with('error','Data gagal ditambahlkan');
    }
    
    public function edit($id){
        $data['result'] = \App\kelas::where('id_kelas',$id)->first();
        return view('kelas/form')->with($data);
    }
    
    public function update(Request $request,$id){
           $rules = [
            'nama_kelas' => 'required|max:100',
            'jurusan' => 'required|max:100'
        ];
        $this->validate($request, $rules); 
        
        $input = $request->all();
        $result = \App\Kelas::where('id_kelas', $id)->first();
        $status = $result->update($input);
        
        if($status) return redirect('/')->with('success', 'Data berhasil diubah');
        else return redirect('/')->with('error','Data gagal diubah');
        
    }
    
    public function destroy(Request $request,$id){
        $result = \App\Kelas::where('id_kelas', $id)->first();
        $status = $result->delete();
        
        if($status) return redirect('/')->with('success', 'Data berhasil dihapus');
        else return redirect('/')->with('error','Data gagal dihapus');
    }
    
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Storage;
use App\Http\Requests;

class SiswaController extends Controller
{
    public function index()
    {
        $data['result'] = \App\Siswa::all();
        return view('siswa/index')->with($data);
    }
    
    public function create()
    {
        return view('siswa/form');
    }
    public function store(Request $request)
    {
        $rules = [
            'nis' => 'required|unique:t_siswa',
            'nama_lengkap' => 'required|max:100',
            'jenis_kelamin' => 'required',
            'alamat' => 'required',
            'no_telp' => 'required',
            'id_kelas' => 'required|exists:t_kelas',
            'foto' => 'required|mimes:jpeg,png|max:512'
        ];
        $this->validate($request, $rules);
        
        $input = $request->all();

        if($request->hasFile('foto') && $request->file('foto')->isValid()){
            $filename = $input['nis'] . "." .$request->file('foto')->getClientOriginalExtension();
            // $request->file('foto')->storeAs('', $filename);
            Storage::disk('upload')->put($filename, file_get_contents($request->file('foto')->getRealPath()));
            $input['foto'] = $filename;
        }
        $status = \App\Siswa::create($input);
        
        if($status) return redirect('siswa')->with('success', 'Data berhasil ditambahkan');
        else return redirect('siswa')->with('error','Data gagal ditambahkan');
    }
    
    public function edit($id)
    {
        $data['result'] = \App\Siswa::where('nis', $id)->first();
        return view('siswa/form')->with($data);
    }
    
    public function update($id, Request $request)
    {
         $rules = [
            'nama_lengkap' => 'required|max:100',
            'jenis_kelamin' => 'required',
            'alamat' => 'required',
            'no_telp' => 'required',
            'id_kelas' => 'required|exists:t_kelas',
            'foto' => 'required|mimes:jpeg,png|max:512',
        ];
         $this->validate($request, $rules);

         $input = $request->all();

         if($request->hasFile('foto') && $request->file('foto')->isValid()){
            $filename = $input['nis'] . "." .$request->file('foto')->getClientOriginalExtension();
            // $request->file('foto')->storeAs('', $filename);
            Storage::disk('upload')->put($filename, file_get_contents($request->file('foto')->getRealPath()));
            $input['foto'] = $filename;
        }

         $result = \App\Siswa::where('nis',$id)->first();
         $status = $result->update($input);
        
        if($status) return redirect('siswa')->with('success', 'Data berhasil diubah');
        else return redirect('siswa')->with('error','Data gagal diubah');
    }
    
    public function destroy(Request $request,$id)
    {
        $result = \App\Siswa::where('nis',$id)->first();
        $status = $result->delete();
        if($status) return redirect('siswa')->with('success', 'Data berhasil dihapus');
        else return redirect('siswa')->with('error','Data gagal dihapus');
    }
}

resources/views/kelas/form.blade.php
@extends('templates/header')  

@section('content')
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
          {{ empty($result) ? 'Tambah' : 'Edit'}} Data Kelas
        <small>SMKN 4 Bandung</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
          <li>Data Kelas</li>
        <li class="active">{{ empty($result) ? 'Tambah' : 'Edit' }} Data Kelas</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        @include('templates/feedback')
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <a href="{{ url('/')}}" class="btn bg-purple"><i class="fa fa-chevron-left"></i>Kembali </a>
          </div>
        
        <div class="box-body">
          
            <form action="{{ empty($result) ? url('kelas/add') : url("kelas/$result->id_kelas/edit")}}" class="form-horizontal" method="post">
            {{csrf_field()}}
                
                @if (!empty($result))
                {{method_field('patch')}}
                @endif
            <div class="form-group">
                <label class="control-label col-sm-2">Nama Kelas</label>
                <div class="col-sm-10">
                <input type="text" name="nama_kelas" class="form-control" placeholder="Masukan Nama Kelas" value="{{ @$result->nama_kelas }}" />
                </div>
                </div>
                
                <div class="form-group">
                <label class="control-label col-sm-2">Jurusan</label>
                <div class="col-sm-10">
                <input type="text" name="jurusan" class="form-control" placeholder="Masukan Jurusan" value="{{ @$result->jurusan }}" />
                </div>
                </div>
                
                <div class="form-group">
                <div class="col-sm-10 colsm-offset-2">
                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i>Simpan </button>
                </div>
                </div>    
            </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          Footer
        </div>
        <!-- /.box-footer-->
      <!-- /.box -->
</div>
    </section>
    <!-- /.content -->
@endsection

resources/views/kelas/index.blade.php
@extends('templates/header')  

@section('content')
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Data Kelas
        <small>SMKN 4 Bandung</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Data Kelas</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        @include('templates/feedback')
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <a href="{{ url('kelas/add')}}" class="btn btn-success"><i class="fa fa-plus-circle"></i>Tambah </a>
          </div>
        
        <div class="box-body">
          <table class="table table-stripped">
            <thead>
              <tr>
                  <th>No</th>
                  <th>Nama Kelas</th>
                  <th>Jurusan</th>
                  <th>Action</th>
                </tr>
              </thead>
              
              <tbody>
                  @foreach ($result as $row)
              <tr>
                  <td>{{ !empty($i)? ++$i :$i = 1}}</td>
                  <td>{{$row->nama_kelas}}</td>
                  <td>{{$row->jurusan}}</td>
                  <td>
                  <a href="{{  url("kelas/$row->id_kelas/edit") }}" class = "btn btn-sm btn-warning" ><i class="fa fa-pencil"></i> </a>
                      
                      <form action="{{ url("kelas/$row->id_kelas/delete") }}" method="POST" style="display:inline;">
                          {{ csrf_field() }}
                          {{ method_field('DELETE')}}
                          
                          <button class="btn btn-sm">
                              <i class="fa fa-trash"></i></button></form>
                  </td>
                  </tr>
                  @endforeach
              </tbody>
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          Footer
        </div>
        <!-- /.box-footer-->
      <!-- /.box -->
</div>
    </section>
    <!-- /.content -->
@endsection

resources/views/login.blade.php
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>1516116265-XIIRPL3-MuhammadRafiShalahudin</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{{ asset('assets') }}/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('assets') }}/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('assets') }}/plugins/iCheck/square/blue.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <a href="{{ asset('assets') }}"><b>Admin</b>LTE</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
      <p class="login-box-msg">Sign in to start your session</p>

      @include('templates.feedback')

      <form action="{{ url('login') }}" method="post">
      {{ csrf_field() }}

        <div class="form-group has-feedback">
          <input type="text" name="username" class="form-control" placeholder="Username">
          <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <input type="password" name="password" class="form-control" placeholder="Password">
          <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>
        <div class="row">
          <div class="col-xs-8">
            <div class="checkbox icheck">
              <label>
                <input type="checkbox" name="remember"> Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <div class="social-auth-links text-center">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
          Facebook</a>
        <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
          Google+</a>
      </div>
      <!-- /.social-auth-links -->

      <a href="#">I forgot my password</a><br>
      <a href="register.html" class="text-center">Register a new membership</a>

    </div>
    <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->

  <!-- jQuery 2.2.3 -->
  <script src="{{ asset('assets') }}/plugins/jQuery/jquery-2.2.3.min.js"></script>
  <!-- Bootstrap 3.3.6 -->
  <script src="{{ asset('assets') }}/bootstrap/js/bootstrap.min.js"></script>
  <!-- iCheck -->
  <script src="{{ asset('assets') }}/plugins/iCheck/icheck.min.js"></script>
  <script>
    $(function () {
      $('input').iCheck({
        checkboxClass: 'icheckbox_square-blue',
        radioClass: 'iradio_square-blue',
        increaseArea: '20%' // optional
      });
    });
  </script>
  </body>
  </html>

resources/views/siswa/form.blade.php
@extends('templates/header')  

@section('content')
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
          {{ empty($result) ? 'Tambah' : 'Edit'}} Data Kelas
        <small>SMKN 4 Bandung</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
          <li>Data Kelas</li>
        <li class="active">{{ empty($result) ? 'Tambah' : 'Edit' }} Data Kelas</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        @include('templates/feedback')
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <a href="{{ url('siswa')}}" class="btn bg-purple"><i class="fa fa-chevron-left"></i>Kembali </a>
          </div>
        
        <div class="box-body">
          
            <form action="{{ empty($result) ? url('siswa/add') : url("siswa/$result->nis/edit")}}" class="form-horizontal" method="post" enctype="multipart/form-data">
            {{csrf_field()}}
                
                @if (!empty($result))
                {{method_field('patch')}}
                @endif
                <div class="form-group">
                <label class="control-label col-sm-2">NIS</label>
                <div class="col-sm-10">
                <input type="text" name="nis" class="form-control" placeholder="Masukan NIS" value="{{ @$result->nis }}" />
                </div>
                </div>
                
                <div class="form-group">
                <label class="control-label col-sm-2">Nama Lengkap</label>
                <div class="col-sm-10">
                <input type="text" name="nama_lengkap" class="form-control" placeholder="Masukan Nama Lengkap" value="{{ @$result->nama_lengkap }}" />
                </div>
                </div>

                <div class="form-group">
                <label class="control-label col-sm-2">Jenis Kelamin</label>
                <div class="col-sm-10">
                <div class="checkbox">
                <label>
                <input type="radio" name="jenis_kelamin" value="L" {{ (@$result->jenis_kelamin == 'L' ? 'checked' : '') }} /> L</label>
                <label>
                <input type="radio" name="jenis_kelamin" value="P" {{ (@$result->jenis_kelamin == 'P' ? 'checked' : '') }} /> P</label>
                </div>
                </div>
                </div>

                <div class="form-group">
                <label class="control-label col-sm-2">Alamat</label>
                <div class="col-sm-10">
                <textarea name="alamat" class="form-control" placeholder="Masukan Alamat" >{{ @$result->alamat }}</textarea> 
                </div>
                </div>

                <div class="form-group">
                <label class="control-label col-sm-2">No Telp</label>
                <div class="col-sm-10">
                <input type="text" name="no_telp" class="form-control" placeholder="Masukan No Telp" value="{{ @$result->no_telp }}" />
                </div>
                </div>

                <div class="form-group">
                <label class="control-label col-sm-2">Kelas</label>
                <div class="col-sm-10">
                <select name="id_kelas" class="form-control">

                @foreach (\App\Kelas::all() as $kelas)
                  <option value="{{ $kelas->id_kelas }}" {{ @$result->id_kelas == $kelas->id_kelas ? 'selected' : '' }}>
                    {{ $kelas->nama_kelas}}
                  </option>
                  @endforeach

                </select>
                </div>
                </div>

                <div class="form-group">
                <label class="control-label col-sm-2 ">Foto</label>

                <div class="col-sm-10">
                <input type="file" name="foto">       

                </div>
           
                
                </div>   


                <div class="form-group">
                <div class="col-sm-10 colsm-offset-2">
                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i>Simpan </button>
                </div>
                </div>    
            </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          Footer
        </div>
        <!-- /.box-footer-->
      <!-- /.box -->
</div>
    </section>
    <!-- /.content -->
@endsection

resources/views/siswa/index.blade.php
@extends('templates/header')  

@section('content')
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Data Siswa
        <small>SMKN 4 Bandung</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('siswa') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Data Siswa</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        @include('templates/feedback')
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <a href="{{ url('siswa/add')}}" class="btn btn-success"><i class="fa fa-plus-circle"></i>Tambah </a>
          </div>
        
        <div class="box-body">
          <table class="table table-stripped">
            <thead>
              <tr>
                  <th>No</th>
                  <th>Foto</th>
                  <th>Nama Lengkap</th>
                  <th>Jenis Kelamin</th>
                  <th>Alamat</th>
                  <th>No Telepon</th>
                  <th>Kelas</th>
                  <th>Action</th>
                </tr>
              </thead>
              
              <tbody>
                  @foreach ($result as $row)
              <tr>
                  <td>{{ !empty($i)? ++$i :$i = 1}}</td>
                  <td><img src="{{url('uploads/' . @$row->foto)}}" width="80px" class="img"></td>
                  <td>{{$row->nama_lengkap}}</td>
                  <td>{{$row->jenis_kelamin_display}}</td>
                  <td>{{$row->alamat}}</td>
                  <td>{{$row->no_telp}}</td>
                  <td>{{$row->kelas->nama_kelas}}</td>
                  <td>
                  <a href="{{  url("siswa/$row->nis/edit") }}" class = "btn btn-sm btn-warning" ><i class="fa fa-pencil"></i> </a>
                      
                      <form action="{{ url("siswa/$row->nis/delete") }}" method="POST" style="display:inline;">
                          {{ csrf_field() }}
                          {{ method_field('DELETE')}}
                          
                          <button class="btn btn-sm btn-danger">
                              <i class="fa fa-trash"></i></button></form>
                  </td>
                  </tr>
                  @endforeach
              </tbody>
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          Footer
        </div>
        <!-- /.box-footer-->
      <!-- /.box -->
</div>
    </section>
    <!-- /.content -->
@endsection

resources/views/templates/feedback.blade.php
@if(session('success'))
    <div class="alert alert-success fade in">
        <button type="button" class="close pull-right" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        {!! session('success') !!}
</div>
@endif

@if(session('error'))
    <div class="alert alert-danger fade in">
<button type="button" class="close pull-right" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        {!! session('error') !!}
</div>
@endif

@if(count($errors) > 0)
    <div class="alert alert-danger fade in">
<button type="button" class="close pull-right" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        <p>Perhatian</p>
        <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
</div>
@endif